# Generated by Django 6.0.3 on 2026-03-29 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refill',
            fields=[
                ('rf_id', models.AutoField(primary_key=True, serialize=False, verbose_name='รหัสการเติมเครดิต')),
                ('rf_date', models.DateTimeField(verbose_name='วันเวลาที่แจ้งเติม')),
                ('rf_money', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='จำนวนเงินที่เติม')),
                ('rf_credit', models.IntegerField(verbose_name='จำนวนเครดิตที่ได้รับ')),
                ('rf_slip', models.ImageField(upload_to='Refill/', verbose_name='สลิปการโอนเงิน')),
                ('rf_confirm_date', models.DateTimeField(blank=True, null=True, verbose_name='วันเวลาที่ยืนยันการเติม')),
                ('rf_status', models.IntegerField(choices=[(0, 'รอตรวจสอบ'), (1, 'ผ่านการตรวจสอบ'), (2, 'ไม่ผ่านการตรวจสอบ')], default=0, verbose_name='สถานะการตรวจสอบ')),
                ('rf_cmt', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.member', verbose_name='รหัสสมาชิก')),
            ],
            options={
                'verbose_name': 'ข้อมูลการเติมเครดิต',
                'db_table': 'refill',
            },
        ),
        migrations.CreateModel(
            name='Withdrawals',
            fields=[
                ('wd_id', models.AutoField(primary_key=True, serialize=False, verbose_name='รหัสการขอถอนเครดิต')),
                ('wd_req_date', models.DateTimeField(verbose_name='วันเวลาที่ขอถอนเครดิต')),
                ('wd_credit', models.IntegerField(verbose_name='จำนวนเครดิตที่ถอน')),
                ('wd_cash', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='จำนวนเงิน (บาท)')),
                ('wd_bank_name', models.CharField(max_length=100, verbose_name='ชื่อธนาคาร')),
                ('wd_acc_name', models.CharField(max_length=100, verbose_name='ชื่อบัญชี')),
                ('wd_acc_no', models.CharField(max_length=20, verbose_name='เลขที่บัญชีธนาคาร')),
                ('wd_fee', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='ค่าธรรมเนียมการถอน')),
                ('wd_paid_date', models.DateTimeField(blank=True, null=True, verbose_name='วันเวลาที่จ่าย')),
                ('wd_status', models.IntegerField(choices=[(0, 'รอดำเนินการ'), (1, 'จ่ายแล้ว'), (2, 'ปฏิเสธการถอน')], default=0, verbose_name='สถานะการจ่าย')),
                ('wd_cmt', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.member', verbose_name='รหัสสมาชิก')),
            ],
            options={
                'verbose_name': 'ข้อมูลการขอถอนเครดิต',
                'db_table': 'withdrawals',
            },
        ),
    ]
