# Generated by Django 5.1.6 on 2026-04-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_withdrawals_add_wd_type_wd_net_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawals',
            name='wd_net_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='ยอดสุทธิที่จ่ายจริง'),
        ),
    ]
