# Generated by Django 6.0.3 on 2026-05-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_alter_withdrawals_wd_net_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawals',
            name='wd_promptpay_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='หมายเลขพร้อมเพย์'),
        ),
    ]
