# Generated by Django 6.0.3 on 2026-05-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0004_withdrawals_wd_promptpay_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='refill',
            name='rf_qr_payload',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ข้อมูล QR จากสลิป'),
        ),
    ]
