# Generated by Django 6.0.3 on 2026-06-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0005_refill_rf_qr_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawals',
            name='wd_status',
            field=models.IntegerField(choices=[(0, 'รอดำเนินการ'), (1, 'จ่ายแล้ว'), (2, 'ปฏิเสธการถอน'), (3, 'ยกเลิกโดยผู้ใช้')], default=0, verbose_name='สถานะการจ่าย'),
        ),
    ]
