# Generated by Django 6.0.3 on 2026-08-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0006_alter_withdrawals_wd_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='refill',
            name='rf_bank_from',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ธนาคารต้นทาง'),
        ),
    ]
