# Generated by Django 6.0.3 on 2026-03-29 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mb_full_name', models.CharField(max_length=100, verbose_name='ชื่อและนามสกุล')),
                ('mb_email', models.CharField(max_length=50, verbose_name='อีเมลมหาวิทยาลัย')),
                ('mb_img', models.ImageField(blank=True, null=True, upload_to='member/', verbose_name='รูปโปรไฟล์')),
                ('mb_deposit_crd', models.IntegerField(default=0, verbose_name='เครดิตนำฝาก')),
                ('mb_income_crd', models.IntegerField(default=0, verbose_name='เครดิตรายได้')),
                ('mb_status', models.IntegerField(choices=[(0, 'ปิดการใช้งาน'), (1, 'ใช้งานปกติ'), (2, 'ระงับชั่วคราว')], default=1, verbose_name='สถานะ')),
                ('mb_locked_crd', models.IntegerField(default=0, verbose_name='เครดิตที่ล็อกไว้')),
                ('mj_id', models.ForeignKey(db_column='mj_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.major', verbose_name='รหัสสาขา')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ข้อมูลสมาชิก',
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('tut_id', models.OneToOneField(db_column='tut_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.member', verbose_name='รหัสติวเตอร์')),
                ('tut_desc', models.TextField(blank=True, null=True, verbose_name='ข้อมูลแนะนำตัว')),
                ('tut_skill', models.TextField(blank=True, null=True, verbose_name='ความถนัด')),
                ('tut_gpax', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='เกรดเฉลี่ย')),
                ('tut_has_exp', models.IntegerField(choices=[(0, 'ไม่เคยสอน'), (1, 'เคยสอน')], default=0, verbose_name='ประสบการณ์สอน')),
                ('tut_exp_desc', models.TextField(blank=True, null=True, verbose_name='รายละเอียดประสบการณ์สอน')),
                ('tut_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='คะแนนรีวิวเฉลี่ย')),
                ('tut_status', models.IntegerField(choices=[(0, 'ยังไม่อนุมัติ'), (1, 'อนุมัติแล้ว'), (2, 'ระงับการสอน')], default=0, verbose_name='สถานะ')),
            ],
            options={
                'verbose_name': 'ข้อมูลติวเตอร์',
                'db_table': 'tutor',
            },
        ),
    ]
