# Generated by Django 5.1.6 on 2026-04-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tut_status',
            field=models.IntegerField(choices=[(0, 'รอการตรวจสอบ'), (1, 'อนุมัติแล้ว'), (2, 'ปฏิเสธ'), (3, 'ระงับการสอน')], default=0, verbose_name='สถานะ'),
        ),
    ]
