# Generated by Django 6.0.3 on 2026-04-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='tut_rating_communication',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='เฉลี่ยการสื่อสารและการอธิบาย'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tut_rating_knowledge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='เฉลี่ยความรู้ความสามารถ'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tut_rating_punctuality',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='เฉลี่ยความตรงต่อเวลา'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tut_rating_quality',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='เฉลี่ยคุณภาพการสอน'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tut_rating_satisfaction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='เฉลี่ยความพึงพอใจ'),
        ),
    ]
