# Generated by Django 6.0.3 on 2026-04-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tutor_tut_rating_communication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='tut_reject_note',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุการปฏิเสธ/ระงับ'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tut_student_card',
            field=models.ImageField(blank=True, null=True, upload_to='tutor_cards/', verbose_name='รูปบัตรนักศึกษา'),
        ),
    ]
