# Generated by Django 6.0.3 on 2026-05-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tutor_tut_reject_note_tutor_tut_student_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mb_img',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/member_profile/', verbose_name='รูปโปรไฟล์'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tut_student_card',
            field=models.ImageField(blank=True, null=True, upload_to='tutoring/tutor_student_cards/', verbose_name='รูปบัตรนักศึกษา'),
        ),
    ]
