# Generated by Django 6.0.3 on 2026-09-18 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_member_mb_img_alter_tutor_tut_student_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorExperienceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tutoring/experience/', verbose_name='รูปประสบการณ์การสอน')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_images', to='accounts.tutor', verbose_name='ติวเตอร์')),
            ],
            options={
                'verbose_name': 'รูปประสบการณ์การสอน',
                'verbose_name_plural': 'รูปประสบการณ์การสอน',
                'db_table': 'tutor_experience_image',
            },
        ),
    ]
