# Generated by Django 6.0.3 on 2026-03-29 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('ib_id', models.AutoField(primary_key=True, serialize=False, verbose_name='รหัสกล่องข้อความ')),
                ('member1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_as_member1', to='accounts.member', verbose_name='รหัสสมาชิกคนที่ 1')),
                ('member2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_as_member2', to='accounts.member', verbose_name='รหัสสมาชิกคนที่ 2')),
            ],
            options={
                'verbose_name': 'ข้อมูลกล่องข้อความ',
                'db_table': 'inbox',
                'unique_together': {('member1', 'member2')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ลำดับข้อความ')),
                ('msg_sent_time', models.DateTimeField(verbose_name='วันเวลาที่ส่ง')),
                ('msg', models.TextField(verbose_name='ข้อความ')),
                ('msg_is_read', models.IntegerField(default=0, verbose_name='สถานะการอ่าน (0=ยังไม่อ่าน, 1=อ่านแล้ว)')),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.inbox', verbose_name='รหัสกล่องข้อความ')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.member', verbose_name='รหัสผู้ส่ง')),
            ],
            options={
                'verbose_name': 'ข้อมูลรายการข้อความ',
                'db_table': 'message',
                'ordering': ['msg_sent_time'],
            },
        ),
    ]
