# Generated by Django 6.0.3 on 2026-04-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg_img',
            field=models.ImageField(blank=True, null=True, upload_to='chat/', verbose_name='รูปภาพในข้อความ'),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg',
            field=models.TextField(blank=True, verbose_name='ข้อความ'),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_sent_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันเวลาที่ส่ง'),
        ),
    ]
