# Generated by Django 6.0.3 on 2026-08-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_msg_img_alter_message_msg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg_is_read',
            field=models.BooleanField(default=False, verbose_name='อ่านแล้ว'),
        ),
    ]
