# Generated by Django 6.0.3 on 2026-03-29 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('cg_id', models.AutoField(primary_key=True, serialize=False, verbose_name='รหัสกลุ่มรายวิชา')),
                ('cg_name', models.CharField(max_length=100, verbose_name='ชื่อกลุ่มรายวิชา')),
                ('cg_desc', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
            ],
            options={
                'verbose_name': 'ข้อมูลกลุ่มรายวิชา',
                'db_table': 'course_group',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('fac_id', models.AutoField(primary_key=True, serialize=False, verbose_name='รหัสคณะ')),
                ('fac_name', models.CharField(max_length=100, verbose_name='ชื่อคณะ')),
            ],
            options={
                'verbose_name': 'ข้อมูลคณะ',
                'db_table': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('crs_id', models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='รหัสรายวิชา')),
                ('crs_name', models.CharField(max_length=150, verbose_name='ชื่อรายวิชา')),
                ('crs_desc', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('cg_id', models.ForeignKey(db_column='cg_id', on_delete=django.db.models.deletion.CASCADE, to='courses.coursegroup', verbose_name='รหัสกลุ่มรายวิชา')),
            ],
            options={
                'verbose_name': 'ข้อมูลรายวิชา',
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('mj_id', models.AutoField(primary_key=True, serialize=False, verbose_name='รหัสสาขา')),
                ('mj_name', models.CharField(max_length=100, verbose_name='ชื่อสาขา')),
                ('mj_abbr', models.CharField(max_length=10, verbose_name='ชื่อย่อสาขา')),
                ('mj_desc', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('fac_id', models.ForeignKey(db_column='fac_id', on_delete=django.db.models.deletion.CASCADE, to='courses.faculty', verbose_name='รหัสคณะ')),
            ],
            options={
                'verbose_name': 'ข้อมูลสาขา',
                'db_table': 'major',
            },
        ),
    ]
