# Generated by Django 6.0.3 on 2026-08-13 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='mj_abbr',
        ),
    ]
