"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import secrets

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name, default=False):
    """อ่านค่า boolean จาก environment โดยรองรับค่าที่ใช้ทั่วไป"""
    value = os.environ.get(name)
    if value is None or value == '':
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def _env_int(name, default=0):
    """อ่านค่าจำนวนเต็มจาก environment และแจ้งชื่อค่าที่ตั้งผิด"""
    value = os.environ.get(name)
    if value is None or value == '':
        return default
    try:
        return int(value)
    except ValueError as error:
        raise ImproperlyConfigured(f'{name} ต้องเป็นจำนวนเต็ม') from error


def _env_list(name, default=''):
    """อ่านรายการที่คั่นด้วย comma จาก environment"""
    value = os.environ.get(name, default)
    return [item.strip() for item in value.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# โหมดพัฒนาจะใช้ค่าเริ่มต้นที่ปลอดภัยต่อเครื่อง local เท่านั้น
DEBUG = _env_bool('DEBUG', True)

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '').strip()
if not SECRET_KEY:
    if DEBUG:
        # ใช้ชั่วคราวเพื่อให้คำสั่งพัฒนาเริ่มทำงานได้ แต่ session จะเปลี่ยนเมื่อ restart
        SECRET_KEY = secrets.token_urlsafe(50)
    else:
        raise ImproperlyConfigured('ต้องกำหนด DJANGO_SECRET_KEY เมื่อ DEBUG=False')

ALLOWED_HOSTS = _env_list(
    'ALLOWED_HOSTS',
    '127.0.0.1,localhost' if DEBUG else '',
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local apps
    'apps.accounts',
    'apps.courses',
    'apps.tutoring',
    'apps.bookings',
    'apps.messaging',
    'apps.credits',
    'apps.admin_panel',
    'apps.notifications',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.admin_panel.middleware.AdminSetupMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            # ลงทะเบียนไลบรารีรูปปกคอร์สให้เทมเพลตเรียกใช้ได้แน่นอน
            'libraries': {
                'course_covers': 'apps.tutoring.templatetags.course_covers',
            },
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.messaging.context_processors.unread_message_count',
                'apps.admin_panel.context_processors.system_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', ''),
        'USER': os.environ.get('DB_USER', ''),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '3306'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'TH-th'

TIME_ZONE = 'Asia/Bangkok'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# ── Static Files ────────────────────────────────────────────
STATIC_URL  = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',   # โฟลเดอร์ static อยู่ root (btt5/, faws6/, …)
]
STATIC_ROOT = BASE_DIR / 'staticfiles'   # สำหรับ collectstatic
 
# ── Media Files ─────────────────────────────────────────────
MEDIA_URL  = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
 
# ── Login / Logout Redirect ──────────────────────────────────
LOGIN_URL          = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
 
# ── Password Reset Token ────────────────────────────────────
PASSWORD_RESET_TIMEOUT = 86400 

# ── Email (SMTP) ─────────────────────────────────────────────
EMAIL_BACKEND   = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST      = 'smtp.gmail.com'
EMAIL_PORT      = 587
EMAIL_USE_TLS   = True
EMAIL_HOST_USER     = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL  = os.environ.get('EMAIL_HOST_USER', 'noreply@rmuti.ac.th')

# Secret สำหรับเปิดหน้าสร้างผู้ดูแลระบบครั้งแรก ใช้เพียงก่อนมี admin ในระบบ
ADMIN_SETUP_TOKEN = os.environ.get('ADMIN_SETUP_TOKEN', '')

# ── Message Storage ─────────────────────────────────────────
from django.contrib.messages import constants as messages_constants
MESSAGE_TAGS = {
    messages_constants.DEBUG:   'secondary',
    messages_constants.INFO:    'info',
    messages_constants.SUCCESS: 'success',
    messages_constants.WARNING: 'warning',
    messages_constants.ERROR:   'danger',
}
 
# ── Development / Production Security ───────────────────────
SKIP_EMAIL_VERIFICATION = _env_bool('SKIP_EMAIL_VERIFICATION', DEBUG)
SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', not DEBUG)
SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', not DEBUG)
SECURE_HSTS_SECONDS = _env_int('SECURE_HSTS_SECONDS', 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', False)
SECURE_HSTS_PRELOAD = _env_bool('SECURE_HSTS_PRELOAD', False)

# กำหนดเวลาของกระบวนการจองเรียน (หน่วย: ชั่วโมงก่อน/หลังเวลาเรียน)
BOOKING_CLOSE_HOURS = 2
TUTOR_RESPONSE_DEADLINE_HOURS = 1
COMPLETION_AUTO_CONFIRM_HOURS = 24
