# Generated by Django 6.0.3 on 2026-03-29 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDate',
            fields=[
                ('sd_id', models.AutoField(primary_key=True, serialize=False, verbose_name='รหัสวันที่เปิดสอน')),
                ('sd_date', models.DateField(verbose_name='วันที่เปิดสอน')),
            ],
            options={
                'verbose_name': 'ข้อมูลวันที่เปิดสอน',
                'db_table': 'schedule_date',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('ts_id', models.AutoField(primary_key=True, serialize=False, verbose_name='รหัสช่วงเวลา')),
                ('ts_start_time', models.TimeField(verbose_name='เวลาเริ่ม')),
                ('ts_end_time', models.TimeField(verbose_name='เวลาจบ')),
                ('sd_id', models.ForeignKey(db_column='sd_id', on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='tutoring.scheduledate', verbose_name='รหัสวันที่เปิดสอน')),
            ],
            options={
                'verbose_name': 'ข้อมูลช่วงเวลาที่เปิดสอน',
                'db_table': 'time_slot',
            },
        ),
        migrations.CreateModel(
            name='TutorCourse',
            fields=[
                ('tutc_id', models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='รหัสรายวิชาที่รับสอน')),
                ('tutc_name', models.CharField(max_length=150, verbose_name='ชื่อรายวิชาเพื่อโฆษณา')),
                ('tutc_desc', models.TextField(blank=True, null=True, verbose_name='รายละเอียดเนื้อหา')),
                ('tutc_img', models.ImageField(blank=True, null=True, upload_to='tutor_course/', verbose_name='รูปปก')),
                ('tutc_max_stu', models.IntegerField(verbose_name='จำนวนรับสูงสุด (คน)')),
                ('tutc_status', models.IntegerField(choices=[(0, 'ปิดรับสอน'), (1, 'เปิดรับสอน')], default=1, verbose_name='สถานะการเปิดสอน')),
                ('crs_id', models.ForeignKey(db_column='crs_id', on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='รหัสรายวิชา')),
                ('tut_id', models.ForeignKey(db_column='tut_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.tutor', verbose_name='รหัสติวเตอร์')),
            ],
            options={
                'verbose_name': 'ข้อมูลรายวิชาที่รับสอน',
                'db_table': 'tutor_course',
            },
        ),
        migrations.AddField(
            model_name='scheduledate',
            name='tutc_id',
            field=models.ForeignKey(db_column='tutc_id', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_dates', to='tutoring.tutorcourse', verbose_name='รหัสรายวิชาที่รับสอน'),
        ),
        migrations.CreateModel(
            name='TutorRate',
            fields=[
                ('tut_rate_id', models.AutoField(primary_key=True, serialize=False, verbose_name='รหัสค่าติว')),
                ('tut_rate_per_person', models.IntegerField(verbose_name='อัตราค่าติว (เครดิต) ต่อคน')),
                ('tut_rate_stu_count', models.IntegerField(verbose_name='เรทตามจำนวนคน')),
                ('tutc_id', models.ForeignKey(db_column='tutc_id', on_delete=django.db.models.deletion.CASCADE, to='tutoring.tutorcourse', verbose_name='รหัสรายวิชาที่รับสอน')),
            ],
            options={
                'verbose_name': 'ข้อมูลอัตราค่าติว',
                'db_table': 'tutor_rate',
            },
        ),
    ]
