# Generated by Django 6.0.3 on 2026-04-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='ts_status',
            field=models.IntegerField(choices=[(0, 'ว่าง'), (1, 'ล็อกแล้ว')], default=0, verbose_name='สถานะช่วงเวลา'),
        ),
    ]
