# Generated by Django 6.0.3 on 2026-05-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0002_timeslot_ts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorcourse',
            name='tutc_img',
            field=models.ImageField(blank=True, null=True, upload_to='tutoring/tutor_img_course/', verbose_name='รูปปก'),
        ),
    ]
