# Generated by Django 6.0.3 on 2026-07-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0003_alter_tutorcourse_tutc_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorcourse',
            name='tutc_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='คะแนนรีวิวเฉลี่ยรายคอร์ส'),
        ),
    ]
