# Generated by Django 6.0.3 on 2026-09-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0004_tutorcourse_tutc_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='ts_meeting_detail',
            field=models.TextField(blank=True, null=True, verbose_name='รายละเอียดนัดหมายของรอบเรียน'),
        ),
        migrations.AddField(
            model_name='tutorcourse',
            name='tutc_meeting_detail',
            field=models.TextField(blank=True, null=True, verbose_name='รายละเอียดนัดหมายเริ่มต้น'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='ts_status',
            field=models.IntegerField(choices=[(0, 'เปิดใช้งาน'), (1, 'สถานะเดิมจากระบบจองแบบหนึ่งรายการ'), (2, 'ปิดรอบ')], default=0, verbose_name='สถานะช่วงเวลา'),
        ),
    ]
