# Generated by Django 6.0.3 on 2026-03-29 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bk_id', models.AutoField(primary_key=True, serialize=False, verbose_name='รหัสการจองเรียน')),
                ('bk_desc', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('bk_stu_datetime', models.DateTimeField(verbose_name='วันเวลาที่นัดเรียน')),
                ('bk_stu_count', models.IntegerField(verbose_name='จำนวนผู้เรียน')),
                ('bk_rate_per_person', models.IntegerField(verbose_name='อัตราค่าติว (เครดิต) ต่อคน')),
                ('bk_date', models.DateTimeField(verbose_name='วันเวลาที่จอง')),
                ('bk_accepted_date', models.DateTimeField(blank=True, null=True, verbose_name='วันเวลาที่รับงาน')),
                ('bk_status', models.IntegerField(choices=[(0, 'จอง'), (1, 'รับงานแล้ว'), (2, 'เรียนแล้ว'), (3, 'แจ้งจบงาน'), (4, 'ยืนยันการจบงาน'), (5, 'รีวิวแล้ว'), (6, 'ปฏิเสธ')], default=0, verbose_name='สถานะ')),
                ('bk_cmt', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.member', verbose_name='รหัสสมาชิก')),
                ('ts_id', models.ForeignKey(blank=True, db_column='ts_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutoring.timeslot', verbose_name='รหัสช่วงเวลา')),
                ('tutc_id', models.ForeignKey(db_column='tutc_id', on_delete=django.db.models.deletion.CASCADE, to='tutoring.tutorcourse', verbose_name='รหัสรายวิชาที่รับสอน')),
            ],
            options={
                'verbose_name': 'ข้อมูลการจองเรียน',
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='JobCompletion',
            fields=[
                ('bk_id', models.OneToOneField(db_column='bk_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bookings.booking', verbose_name='รหัสการจองเรียน')),
                ('jc_complete_date', models.DateTimeField(verbose_name='วันเวลาที่แจ้งจบงาน')),
                ('jc_confirm_date', models.DateTimeField(blank=True, null=True, verbose_name='วันเวลาที่ยืนยัน')),
            ],
            options={
                'verbose_name': 'ข้อมูลการแจ้งจบงาน',
                'db_table': 'job_completion',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('bk_id', models.OneToOneField(db_column='bk_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bookings.booking', verbose_name='รหัสการจองเรียน')),
                ('rv_quality', models.IntegerField(verbose_name='คะแนนคุณภาพการสอน')),
                ('rv_knowledge', models.IntegerField(verbose_name='คะแนนความรู้ความสามารถ')),
                ('rv_communication', models.IntegerField(verbose_name='คะแนนการสื่อสารและการอธิบาย')),
                ('rv_punctuality', models.IntegerField(verbose_name='คะแนนความตรงต่อเวลา')),
                ('rv_satisfaction', models.IntegerField(verbose_name='คะแนนความพึงพอใจ')),
                ('rv_cmt', models.TextField(blank=True, null=True, verbose_name='ข้อความรีวิว')),
                ('rv_date', models.DateTimeField(verbose_name='วันเวลาที่บันทึก')),
            ],
            options={
                'verbose_name': 'ข้อมูลการรีวิว',
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='TutoringActivity',
            fields=[
                ('bk_id', models.OneToOneField(db_column='bk_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bookings.booking', verbose_name='รหัสการจองเรียน')),
                ('ta_img1', models.ImageField(blank=True, null=True, upload_to='tutoring/', verbose_name='รูปภาพการสอน 1')),
                ('ta_img2', models.ImageField(blank=True, null=True, upload_to='tutoring/', verbose_name='รูปภาพการสอน 2')),
                ('ta_img3', models.ImageField(blank=True, null=True, upload_to='tutoring/', verbose_name='รูปภาพการสอน 3')),
                ('ta_desc', models.TextField(blank=True, null=True, verbose_name='รายละเอียดเพิ่มเติม')),
            ],
            options={
                'verbose_name': 'ข้อมูลกิจกรรมการติว',
                'db_table': 'tutoring_activity',
            },
        ),
    ]
