# Generated by Django 6.0.3 on 2026-04-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bk_report_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันเวลาที่รายงาน'),
        ),
        migrations.AddField(
            model_name='booking',
            name='bk_report_desc',
            field=models.TextField(blank=True, null=True, verbose_name='รายละเอียดการรายงานปัญหา'),
        ),
        migrations.AddField(
            model_name='booking',
            name='bk_report_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='ประเภทการรายงาน (0=ติวเตอร์, 1=แอดมิน)'),
        ),
    ]
