# Generated by Django 6.0.3 on 2026-04-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_bk_report_date_booking_bk_report_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bk_report_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='bk_report_reason',
            field=models.CharField(blank=True, choices=[('1', 'หลักฐานการสอนไม่ตรงความจริง'), ('2', 'ไม่ได้สอนเลยแต่แจ้งจบงาน'), ('3', 'เนื้อหาไม่ตรงที่ตกลงไว้'), ('4', 'ผู้เรียนกดยืนยันโดยไม่ตั้งใจ'), ('other', 'อื่นๆ')], max_length=10, null=True, verbose_name='สาเหตุการรายงานปัญหา'),
        ),
    ]
