# Generated by Django 6.0.3 on 2026-04-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_bk_report_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bk_report_resolved_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันเวลาที่จัดการรายงาน'),
        ),
    ]
