# Generated by Django 6.0.3 on 2026-05-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_bk_report_resolved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringactivity',
            name='ta_img1',
            field=models.ImageField(blank=True, null=True, upload_to='tutoring/activity/', verbose_name='รูปภาพการสอน 1'),
        ),
        migrations.AlterField(
            model_name='tutoringactivity',
            name='ta_img2',
            field=models.ImageField(blank=True, null=True, upload_to='tutoring/activity/', verbose_name='รูปภาพการสอน 2'),
        ),
        migrations.AlterField(
            model_name='tutoringactivity',
            name='ta_img3',
            field=models.ImageField(blank=True, null=True, upload_to='tutoring/activity/', verbose_name='รูปภาพการสอน 3'),
        ),
    ]
