# Generated by Django 6.0.3 on 2026-06-03 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_member_mb_img_alter_tutor_tut_student_card'),
        ('bookings', '0005_alter_tutoringactivity_ta_img1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingReportStatement',
            fields=[
                ('brs_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Report statement ID')),
                ('brs_role', models.CharField(choices=[('student', 'Student'), ('tutor', 'Tutor')], max_length=10, verbose_name='Role')),
                ('brs_desc', models.TextField(verbose_name='Statement detail')),
                ('brs_date', models.DateTimeField(verbose_name='Statement date')),
                ('bk_id', models.ForeignKey(db_column='bk_id', on_delete=django.db.models.deletion.CASCADE, related_name='report_statements', to='bookings.booking', verbose_name='Booking')),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.member', verbose_name='Statement owner')),
            ],
            options={
                'verbose_name': 'Booking report statement',
                'db_table': 'booking_report_statement',
                'ordering': ['brs_date', 'brs_id'],
            },
        ),
    ]
