# Generated by Django 6.0.3 on 2026-08-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_bookingreportstatement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bk_report_reason',
            field=models.CharField(blank=True, choices=[('1', 'หลักฐานการสอนไม่ตรงความจริง'), ('2', 'ติวเตอร์ไม่เข้าสอน'), ('3', 'เนื้อหาไม่ตรงที่ตกลงไว้'), ('5', 'ผู้เรียนไม่เข้าเรียน'), ('6', 'ติดต่ออีกฝ่ายไม่ได้'), ('7', 'ไม่สามารถตกลงกันได้'), ('8', 'อื่น ๆ')], max_length=10, null=True, verbose_name='สาเหตุการรายงานปัญหา'),
        ),
    ]
