# Generated by Django 6.0.3 on 2026-03-29 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_name', models.CharField(max_length=100, verbose_name='ชื่อมหาวิทยาลัย')),
                ('bank_name', models.CharField(max_length=100, verbose_name='ชื่อธนาคาร')),
                ('acc_name', models.CharField(max_length=100, verbose_name='ชื่อบัญชี')),
                ('acc_no', models.CharField(max_length=20, verbose_name='เลขที่บัญชีธนาคาร')),
                ('crd_val', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='มูลค่าเครดิต')),
                ('deposit_withdraw_fee_pct', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='อัตราร้อยละค่าธรรมเนียมการถอนยอดเครดิตนำฝาก')),
                ('income_withdraw_fee_pct', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='อัตราร้อยละค่าธรรมเนียมการถอนยอดเครดิตรายได้')),
                ('admin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ดูแลระบบ')),
            ],
            options={
                'verbose_name': 'ข้อมูลระบบ',
                'db_table': 'system',
            },
        ),
    ]
