# Generated by Django 5.1.6 on 2026-04-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_system_crd_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
