# Generated by Django 6.0.3 on 2026-04-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_system_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='promptpay_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='หมายเลขพร้อมเพย์ (เบอร์โทร/เลขบัตรประชาชน)'),
        ),
    ]
