# Generated by Django 6.0.3 on 2026-05-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_system_promptpay_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='total_accumulated_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ค่าธรรมเนียมสะสมทั้งหมด'),
        ),
    ]
