# Generated by Django 6.0.3 on 2026-06-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_system_total_accumulated_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='email_domain',
            field=models.CharField(default='rmuti.ac.th', max_length=100, verbose_name='โดเมนอีเมลมหาวิทยาลัย'),
        ),
    ]
