# Generated by Django 6.0.3 on 2026-04-24 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_tutor_tut_rating_communication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('booking_new', 'มีการจองติวใหม่'), ('booking_accepted', 'การจองได้รับการยืนยัน'), ('booking_rejected', 'การจองถูกปฏิเสธ'), ('booking_completed', 'มีการแจ้งจบงานที่ต้องยืนยัน'), ('booking_credited', 'งานเสร็จสิ้น ได้รับเครดิตแล้ว'), ('booking_reviewed', 'มีรีวิวใหม่'), ('booking_reported', 'มีการรายงานปัญหา'), ('tutor_approved', 'ติวเตอร์ได้รับการอนุมัติ'), ('tutor_rejected', 'ติวเตอร์ถูกปฏิเสธ'), ('tutor_suspended', 'บัญชีติวเตอร์ถูกระงับ'), ('refill_approved', 'เติมเครดิตผ่านการตรวจสอบ'), ('refill_rejected', 'เติมเครดิตไม่ผ่านการตรวจสอบ'), ('withdraw_paid', 'ถอนเงินเข้าบัญชีเรียบร้อย'), ('admin_refill', 'มีคำขอเติมเครดิต'), ('admin_withdraw', 'มีคนขอถอนเครดิต'), ('admin_tutor_new', 'มีติวเตอร์สมัครใหม่รอ approve'), ('admin_reported', 'มีการรายงานปัญหา')], max_length=30, verbose_name='ประเภท')),
                ('notif_text', models.CharField(max_length=255, verbose_name='ข้อความแจ้งเตือน')),
                ('notif_url', models.CharField(blank=True, default='', max_length=255, verbose_name='ลิงก์ปลายทาง')),
                ('notif_is_read', models.BooleanField(default=False, verbose_name='อ่านแล้ว')),
                ('notif_created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันเวลาที่สร้าง')),
                ('admin_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับ (Admin)')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.member', verbose_name='ผู้รับ (Member)')),
            ],
            options={
                'verbose_name': 'การแจ้งเตือน',
                'db_table': 'notification',
                'ordering': ['-notif_created_at'],
            },
        ),
    ]
