# Generated by Django 6.0.3 on 2026-08-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('booking_new', 'มีการจองติวใหม่'), ('booking_accepted', 'การจองได้รับการยืนยัน'), ('booking_rejected', 'การจองถูกปฏิเสธ'), ('booking_completed', 'มีการแจ้งจบงานที่ต้องยืนยัน'), ('booking_credited', 'งานเสร็จสิ้น ได้รับเครดิตแล้ว'), ('booking_reviewed', 'มีรีวิวใหม่'), ('booking_reported', 'มีการรายงานปัญหา'), ('booking_cancel_requested', 'มีคำขอยกเลิกการเรียน'), ('booking_cancel_rejected', 'คำขอยกเลิกไม่ได้รับการอนุมัติ'), ('booking_cancelled', 'การจองหรือการเรียนถูกยกเลิก'), ('booking_report_statement', 'มีคำชี้แจงเพิ่มเติมในรายงาน'), ('booking_report_resolved', 'รายงานได้รับการพิจารณาแล้ว'), ('tutor_approved', 'ติวเตอร์ได้รับการอนุมัติ'), ('tutor_rejected', 'ติวเตอร์ถูกปฏิเสธ'), ('tutor_suspended', 'บัญชีติวเตอร์ถูกระงับ'), ('refill_approved', 'เติมเครดิตผ่านการตรวจสอบ'), ('refill_rejected', 'เติมเครดิตไม่ผ่านการตรวจสอบ'), ('withdraw_paid', 'ถอนเงินเข้าบัญชีเรียบร้อย'), ('admin_refill', 'มีคำขอเติมเครดิต'), ('admin_withdraw', 'มีคนขอถอนเครดิต'), ('admin_tutor_new', 'มีติวเตอร์สมัครใหม่รอ approve'), ('admin_reported', 'มีการรายงานปัญหา')], max_length=30, verbose_name='ประเภท'),
        ),
    ]
