# Generated by Django 6.0.3 on 2026-08-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notif_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='id',
        ),
        migrations.AddField(
            model_name='notification',
            name='notif_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='รหัสการแจ้งเตือน'),
        ),
    ]
